import React from 'react'
import { JobsTable } from './table/data-table'
import { columns, Job } from './table/columns'

const page = () => {

  const data: Job[] = [
    {
      id: "1",
      title: "Software Engineer",
      company: "Tech Innovators",
      industry: "technology",
      description: "Develop and maintain scalable web applications.",
      salary: "4500-6000",
      contact: "hr@techinnovators.com",
      location: "Seoul, South Korea",
    },
    {
      id: "2",
      title: "Financial Analyst",
      company: "Future Finance Co.",
      industry: "finance",
      description: "Analyze market trends and provide investment strategies.",
      salary: "4000-5500",
      contact: "careers@futurefinance.com",
      location: "Seoul, South Korea",
    },
    {
      id: "3",
      title: "Nurse",
      company: "HealthFirst Hospital",
      industry: "healthcare",
      description: "Provide patient care and assist in medical procedures.",
      salary: "3000-4500",
      contact: "apply@healthfirst.com",
      location: "Seoul, South Korea",
    },
    {
      id: "4",
      title: "University Lecturer",
      company: "Global University",
      industry: "education",
      description: "Teach undergraduate courses in computer science.",
      salary: "3500-5000",
      contact: "faculty@globaluniversity.com",
      location: "Seoul, South Korea",
    },
    {
      id: "5",
      title: "Store Manager",
      company: "Urban Trends Retail",
      industry: "retail",
      description: "Oversee store operations and manage staff.",
      salary: "3000-4000",
      contact: "jobs@urbantrends.com",
      location: "Seoul, South Korea",
    },
    {
      id: "6",
      title: "Mechanical Engineer",
      company: "Prime Manufacturing Co.",
      industry: "manufacturing",
      description: "Design and develop mechanical systems for production.",
      salary: "4500-6000",
      contact: "recruit@primemanufacturing.com",
      location: "Seoul, South Korea",
    },
    {
      id: "7",
      title: "Hotel Manager",
      company: "Luxury Stay Hotels",
      industry: "hospitality",
      description: "Manage hotel operations and ensure guest satisfaction.",
      salary: "5000-6500",
      contact: "apply@luxurystay.com",
      location: "Seoul, South Korea",
    },
    {
      id: "8",
      title: "Civil Engineer",
      company: "BuildSmart Constructions",
      industry: "construction",
      description: "Plan and execute construction projects.",
      salary: "4000-5500",
      contact: "careers@buildsmart.com",
      location: "Seoul, South Korea",
    },
    {
      id: "9",
      title: "Graphic Designer",
      company: "Vision Media Group",
      industry: "media",
      description: "Create visual concepts for advertising and branding.",
      salary: "3500-4500",
      contact: "design@visionmedia.com",
      location: "Seoul, South Korea",
    },
    {
      id: "10",
      title: "Logistics Manager",
      company: "Swift Transport Solutions",
      industry: "transportation",
      description: "Coordinate and manage supply chain operations.",
      salary: "4500-6000",
      contact: "hr@swifttransport.com",
      location: "Seoul, South Korea",
    },
    {
      id: "11",
      title: "Data Scientist",
      company: "AI Innovators",
      industry: "technology",
      description: "Analyze large datasets to derive actionable insights.",
      salary: "5000-7000",
      contact: "jobs@aiinnovators.com",
      location: "Seoul, South Korea",
    },
    {
      id: "12",
      title: "Investment Banker",
      company: "Core Capital",
      industry: "finance",
      description: "Manage financial portfolios and investment opportunities.",
      salary: "7000-10000",
      contact: "apply@corecapital.com",
      location: "Seoul, South Korea",
    },
    {
      id: "13",
      title: "Pharmacist",
      company: "CityHealth Pharmacy",
      industry: "healthcare",
      description: "Dispense medications and advise patients on prescriptions.",
      salary: "4000-5000",
      contact: "careers@cityhealth.com",
      location: "Seoul, South Korea",
    },
    {
      id: "14",
      title: "High School Teacher",
      company: "Future Academy",
      industry: "education",
      description: "Teach mathematics to high school students.",
      salary: "3500-4500",
      contact: "teachers@futureacademy.com",
      location: "Seoul, South Korea",
    },
    {
      id: "15",
      title: "Retail Associate",
      company: "CityStyle Boutique",
      industry: "retail",
      description: "Assist customers and manage inventory in the store.",
      salary: "2500-3500",
      contact: "hr@citystyle.com",
      location: "Seoul, South Korea",
    },
    {
      id: "16",
      title: "Production Supervisor",
      company: "Mega Factory Ltd.",
      industry: "manufacturing",
      description: "Oversee production processes and ensure efficiency.",
      salary: "4000-5000",
      contact: "jobs@megafactory.com",
      location: "Seoul, South Korea",
    },
    {
      id: "17",
      title: "Event Coordinator",
      company: "Prestige Events",
      industry: "hospitality",
      description: "Plan and execute events for corporate clients.",
      salary: "3500-4500",
      contact: "careers@prestigeevents.com",
      location: "Seoul, South Korea",
    },
    {
      id: "18",
      title: "Architect",
      company: "Modern Designs Ltd.",
      industry: "construction",
      description: "Design innovative and sustainable buildings.",
      salary: "5000-7000",
      contact: "apply@moderndesigns.com",
      location: "Seoul, South Korea",
    },
    {
      id: "19",
      title: "Content Writer",
      company: "Creative Media Group",
      industry: "media",
      description: "Write engaging content for digital platforms.",
      salary: "3000-4000",
      contact: "jobs@creativemedia.com",
      location: "Seoul, South Korea",
    },
    {
      id: "20",
      title: "Fleet Manager",
      company: "Speed Logistics",
      industry: "transportation",
      description: "Manage fleet operations and vehicle maintenance.",
      salary: "4500-5500",
      contact: "careers@speedlogistics.com",
      location: "Seoul, South Korea",
    },
  ];
  return <JobsTable columns={columns} data={data} />;
}

export default page
