import React from 'react'
import { StudentTable } from './table/data-table'
import { columns, Student } from './table/columns'
import { delay } from '@/lib/utils'

const page =  () => {

  const data: Student[] = [
    {
      id: "1",
      name: "Seoul National University",
      description: "Top-ranked university in South Korea.",
      category: "university",
      location: "1 Gwanak-ro, Gwanak-gu, Seoul",
      contact: "+82 2-880-5114",
      lat: 37.4599,
      lng: 126.9517,
    },
    {
      id: "2",
      name: "Yonsei University",
      description:
        "Leading private university known for its research programs.",
      category: "university",
      location: "50 Yonsei-ro, Seodaemun-gu, Seoul",
      contact: "+82 2-2123-2114",
      lat: 37.5658,
      lng: 126.9386,
    },
    {
      id: "3",
      name: "Daechi-dong Library",
      description: "Public library with excellent study resources.",
      category: "library",
      location: "1298-31 Seocho-dong, Seocho-gu, Seoul",
      contact: "+82 2-570-9999",
      lat: 37.4954,
      lng: 127.0624,
    },
    {
      id: "4",
      name: "Kangnam Coaching Center",
      description: "Popular coaching center for university entrance exams.",
      category: "coaching_center",
      location: "23-1 Teheran-ro, Gangnam-gu, Seoul",
      contact: "+82 2-3456-7890",
      lat: 37.5068,
      lng: 127.0554,
    },
    {
      id: "5",
      name: "Maple Grove International School",
      description: "An international school offering IB curriculum.",
      category: "school",
      location: "45 Maple St, Yongsan-gu, Seoul",
      contact: "+82 2-9876-5432",
      lat: 37.5313,
      lng: 126.9815,
    },
    {
      id: "6",
      name: "Korea University",
      description: "Known for its prestigious law and business programs.",
      category: "university",
      location: "145 Anam-ro, Seongbuk-gu, Seoul",
      contact: "+82 2-3290-1114",
      lat: 37.5892,
      lng: 127.0324,
    },
    {
      id: "7",
      name: "Songpa District Library",
      description: "Quiet library ideal for students.",
      category: "library",
      location: "24 Songpa-ro, Songpa-gu, Seoul",
      contact: "+82 2-1111-2222",
      lat: 37.5146,
      lng: 127.1035,
    },
    {
      id: "8",
      name: "Top Grade Coaching Center",
      description: "Specialized in STEM subjects for high school students.",
      category: "coaching_center",
      location: "47 Science Park Ave, Gwanak-gu, Seoul",
      contact: "+82 2-6543-2100",
      lat: 37.4803,
      lng: 126.9607,
    },
    {
      id: "9",
      name: "Hannam Elementary School",
      description: "Reputed elementary school in the city center.",
      category: "school",
      location: "12 Hannam-dong, Yongsan-gu, Seoul",
      contact: "+82 2-1234-5678",
      lat: 37.5385,
      lng: 126.9987,
    },
    {
      id: "10",
      name: "Dongdaemun Public Library",
      description: "Resource-rich library with e-learning tools.",
      category: "library",
      location: "32 Dongdaemun-ro, Jung-gu, Seoul",
      contact: "+82 2-3030-4040",
      lat: 37.5703,
      lng: 127.0092,
    },
    {
      id: "11",
      name: "Sejong Academy of Arts and Sciences",
      description: "Elite school for gifted students.",
      category: "school",
      location: "56 Art St, Gangseo-gu, Seoul",
      contact: "+82 2-5555-7777",
      lat: 37.5567,
      lng: 126.8365,
    },
    {
      id: "12",
      name: "Elite Math Coaching Center",
      description: "Focused on advanced math preparation.",
      category: "coaching_center",
      location: "88 Education St, Seocho-gu, Seoul",
      contact: "+82 2-9876-5432",
      lat: 37.4812,
      lng: 127.0185,
    },
    {
      id: "13",
      name: "Guro Digital Library",
      description: "Equipped with a large collection of technical books.",
      category: "library",
      location: "98 Tech Park Ave, Guro-gu, Seoul",
      contact: "+82 2-4701-1302",
      lat: 37.5038,
      lng: 126.8796,
    },
    {
      id: "14",
      name: "Changdong High School",
      description: "Renowned for its academic excellence.",
      category: "school",
      location: "7 Changdong, Dobong-gu, Seoul",
      contact: "+82 2-2345-6789",
      lat: 37.6538,
      lng: 127.0463,
    },
    {
      id: "15",
      name: "Hanyang University",
      description: "Famous for its engineering programs.",
      category: "university",
      location: "222 Wangsimni-ro, Seongdong-gu, Seoul",
      contact: "+82 2-2220-0114",
      lat: 37.5585,
      lng: 127.0458,
    },
    {
      id: "16",
      name: "Lotte Academy Coaching Center",
      description: "Offers coaching for business and management studies.",
      category: "coaching_center",
      location: "90 Lotte St, Songpa-gu, Seoul",
      contact: "+82 2-5678-9012",
      lat: 37.5149,
      lng: 127.1056,
    },
    {
      id: "17",
      name: "Dongjak Public Library",
      description: "Known for its quiet and spacious study areas.",
      category: "library",
      location: "17 Library St, Dongjak-gu, Seoul",
      contact: "+82 2-0001-5678",
      lat: 37.4969,
      lng: 126.9431,
    },
    {
      id: "18",
      name: "Sunhwa Arts School",
      description: "A specialized school for performing arts.",
      category: "school",
      location: "41 Arts Ave, Jung-gu, Seoul",
      contact: "+82 2-1212-3434",
      lat: 37.5611,
      lng: 126.9751,
    },
    {
      id: "19",
      name: "Seoul Science High School",
      description: "Focused on science and innovation.",
      category: "school",
      location: "16 Innovation Blvd, Jongno-gu, Seoul",
      contact: "+82 2-3333-4444",
      lat: 37.5744,
      lng: 126.9835,
    },
    {
      id: "20",
      name: "Namsan Library",
      description: "A historic library with modern amenities.",
      category: "library",
      location: "5 Namsan-dong, Jung-gu, Seoul",
      contact: "+82 2-1010-2323",
      lat: 37.5517,
      lng: 126.9912,
    },
  ];
  return <StudentTable columns={columns} data={data} />;
}

export default page
